/*
  Radix Colors, as plain custom properties: every hue the app paints.

  Writes app/styles/generated/radix.css from the installed @radix-ui/colors package. Run
  it after changing the package version, or after a stylesheet starts reading
  a scale it did not read before -- `pnpm colors:radix` -- and commit the
  result. `pnpm check:tokens` fails on a step read from a scale not emitted.

  Why generated rather than imported. Radix's own stylesheets switch themes with
  a .dark class and reuse the light names for the dark scale, while this app
  themes with light-dark(). So both themes are published side by side --
  --radix-<scale>-<step> and --radix-<scale>-dark-<step> -- and a role picks
  between the two with light-dark() like every other token.

  Why not @theme. A theme variable becomes a utility, and markup reaches colour
  through a role, never a palette step. So these are plain properties on
  :root, and only the scales some stylesheet reads are written: the list is
  derived from the CSS rather than kept here. P3 values, exact on a wide-gamut
  display and mapped into gamut by the browser elsewhere.
*/

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as radix from '@radix-ui/colors';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUTPUT = join(ROOT, 'app/styles/generated/radix.css');
const STYLESHEETS = ['app', 'components'];
const STEPS = 12;

type Scale = Record<string, string>;
const exports = radix as unknown as Record<string, Scale | undefined>;

const version = (
  JSON.parse(
    readFileSync(
      new URL(import.meta.resolve('@radix-ui/colors/package.json')),
      'utf8',
    ),
  ) as { version: string }
).version;

function walk(dir: string): string[] {
  return readdirSync(join(ROOT, dir)).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(join(ROOT, path)).isDirectory()) return walk(path);
    return entry.endsWith('.css') ? [path] : [];
  });
}

const read = new Set<string>();
for (const path of STYLESHEETS.flatMap(walk)) {
  if (join(ROOT, path) === OUTPUT) continue;
  const css = readFileSync(join(ROOT, path), 'utf8');
  for (const [, scale] of css.matchAll(
    /var\(--radix-([a-z]+)-(?:dark-)?\d+\)/g,
  )) {
    read.add(scale!);
  }
}

const scales = [...read].sort();
for (const name of scales) {
  if (!exports[`${name}P3`] || !exports[`${name}DarkP3`]) {
    throw new Error(`@radix-ui/colors has no P3 light and dark ${name} scale`);
  }
}

function declarations(name: string, theme: 'light' | 'dark') {
  const scale = exports[theme === 'light' ? `${name}P3` : `${name}DarkP3`]!;
  const infix = theme === 'light' ? '' : 'dark-';
  return Array.from({ length: STEPS }, (_, index) => {
    const step = index + 1;
    const value = scale[`${name}${step}`];
    if (!value) throw new Error(`${name} ${theme} is missing step ${step}`);
    return `  --radix-${name}-${infix}${step}: ${value};`;
  });
}

const blocks = scales.map((name) =>
  [...declarations(name, 'light'), ...declarations(name, 'dark')].join('\n'),
);

const css = `/*
  Radix Colors ${version} (MIT): ${scales.join(', ')}.
  Generated by scripts/generate-radix-colors.ts -- do not edit by hand; run
  \`pnpm colors:radix\` after changing the package version or reading a new
  scale.
*/
:root {
${blocks.join('\n\n')}
}
`;

writeFileSync(OUTPUT, css);
process.stdout.write(
  `app/styles/generated/radix.css: ${scales.length} scales, ${scales.length * STEPS * 2} colours (Radix ${version})\n`,
);
