/*
  Four neutral palettes Tailwind does not ship, in Tailwind's own shape.

  Writes app/neutral-palettes.css. Run it after changing a signature below --
  `pnpm colors:neutrals` -- and commit the result.

  Why these are generated rather than hand-picked. Tailwind's five neutrals are
  one ramp wearing five signatures: slate, gray, zinc, neutral and stone agree
  on lightness at every step to within half a percent, and differ only in
  chroma and hue. So a new neutral is not eleven colours to choose, it is a hue
  and a chroma curve over a lightness curve that already exists. The curve is
  read back out of the installed Tailwind rather than copied here, so these
  four follow it if Tailwind ever retunes it.

  What is left to taste is the SIGNATURES table: a hue, and whose chroma curve
  to borrow and how far to push it. Chroma is borrowed rather than written
  because its shape along a ramp -- rising to a mid peak, easing off in the
  shadows -- is what keeps a neutral from going muddy at one end and garish at
  the other, and Tailwind has already solved that four times over.
*/

import { readFileSync, writeFileSync } from 'node:fs';

const OUTPUT = new URL('../app/neutral-palettes.css', import.meta.url);
const TAILWIND = new URL(import.meta.resolve('tailwindcss/theme.css'));

/* The family whose shared lightness curve every neutral here is cut from. */
const FAMILY = ['slate', 'gray', 'zinc', 'neutral', 'stone'] as const;
const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

/*
  Hue in oklch degrees, and the chroma curve to borrow. `scale` multiplies that
  curve at every step, so a palette stays proportioned like the one it borrows
  from however far it is pushed. These four are the tuning surface: change a
  number, re-run, look at it.
*/
const SIGNATURES = {
  /* Warm grey-brown: stone pushed past stone, a little further from grey. */
  taupe: { hue: 68, chroma: 'stone', scale: 1.5 },
  /* Pink-grey: zinc's restraint, turned off blue and onto red. */
  mauve: { hue: 318, chroma: 'zinc', scale: 1.8 },
  /* Cool blue-grey: gray's curve as-is, carried further toward blue. */
  mist: { hue: 228, chroma: 'gray', scale: 1.0 },
  /* Green-grey: stone's curve, swung to the other side of neutral. */
  olive: { hue: 128, chroma: 'stone', scale: 1.6 },
} satisfies Record<string, { hue: number; chroma: string; scale: number }>;

type Step = { l: number; c: number };
const source = readFileSync(TAILWIND, 'utf8');

function ramp(name: string): Map<number, Step> {
  const steps = new Map<number, Step>();
  const pattern = new RegExp(
    `--color-${name}-(\\d+):\\s*oklch\\(([\\d.]+)%\\s+([\\d.]+)\\s+(?:none|[\\d.]+)\\)`,
    'g',
  );
  for (const [, step, l, c] of source.matchAll(pattern)) {
    steps.set(Number(step), { l: Number(l), c: Number(c) });
  }
  for (const step of STEPS) {
    if (!steps.has(step)) {
      throw new Error(`tailwindcss/theme.css has no --color-${name}-${step}`);
    }
  }
  return steps;
}

const family = FAMILY.map(ramp);

/*
  The shared curve, as the mean of the family at each step. A mean rather than
  one palette's copy: no member is the canonical one, and averaging keeps a
  single outlier (the 950s drift apart by nearly two percent) from deciding it.
*/
const lightness = new Map(
  STEPS.map((step) => {
    const values = family.map((steps) => steps.get(step)!.l);
    const mean = values.reduce((sum, l) => sum + l, 0) / values.length;
    return [step, Math.round(mean * 10) / 10];
  }),
);

const spread = Math.max(
  ...STEPS.map((step) => {
    const values = family.map((steps) => steps.get(step)!.l);
    return Math.max(...values) - Math.min(...values);
  }),
);

const blocks = Object.entries(SIGNATURES).map(([name, signature]) => {
  const borrowed = ramp(signature.chroma);
  const declarations = STEPS.map((step) => {
    const chroma = borrowed.get(step)!.c * signature.scale;
    const value = `oklch(${lightness.get(step)}% ${
      Math.round(chroma * 1000) / 1000
    } ${signature.hue})`;
    return `  --color-${name}-${step}: ${value};`;
  });
  return [
    `  /* ${name}: ${signature.chroma}'s chroma x${signature.scale} at h${signature.hue} */`,
    ...declarations,
  ].join('\n');
});

const css = `/*
  Taupe, mauve, mist and olive -- four neutrals in Tailwind's shape, cut from
  the lightness curve its own five neutrals share. Generated by
  scripts/generate-neutral-palettes.ts -- do not edit by hand; run
  \`pnpm colors:neutrals\` after changing a signature there.

  Inside @theme so Tailwind emits only the steps something reads, and so these
  sit beside --color-zinc-* under the same name shape: the ramps in tokens.css
  bind a palette by name and cannot tell a generated one from a shipped one.
*/
@theme {
${blocks.join('\n\n')}
}
`;

writeFileSync(OUTPUT, css);
process.stdout.write(
  `app/neutral-palettes.css: ${Object.keys(SIGNATURES).length} palettes x ${
    STEPS.length
  } steps, on the ${FAMILY.length}-neutral mean curve (family spread ${
    Math.round(spread * 10) / 10
  }%)\n`,
);
