/*
  Radix Colors, as Tailwind theme variables.

  Writes app/radix-colors.css from the installed @radix-ui/colors package: every
  scale, all twelve steps, light and dark. Run it after changing the package
  version -- `pnpm colors:radix` -- and commit the result.

  Why generated rather than imported. Radix's own stylesheets switch themes with
  a .dark class and reuse the light names for the dark scale, while this app
  themes with light-dark(), driven by the colour scheme of whichever subtree a
  colour is used in. So both themes are published side by side under their own
  names -- --color-radix-<scale>-<step> and --color-radix-<scale>-dark-<step>
  -- and whatever reads them picks between the two with light-dark() like every
  other token. (Placeholders rather than a real name: Tailwind scans this file,
  and a real one here would be emitted as though a style read it.)

  Why @theme, and why P3. Tailwind emits a theme variable only if something
  uses it, so the whole set costs nothing until a colour is actually read. A
  theme variable holds one value, so each step takes Radix's P3 value: exact on
  a wide-gamut display, and mapped into gamut by the browser elsewhere. The
  alpha scales are left out until something needs them.
*/

import { readFileSync, writeFileSync } from 'node:fs';
import * as radix from '@radix-ui/colors';

const OUTPUT = new URL('../app/radix-colors.css', import.meta.url);
const STEPS = 12;

type Scale = Record<string, string>;
const exports = radix as unknown as Record<string, Scale | undefined>;

const version = (
  JSON.parse(
    readFileSync(
      new URL(import.meta.resolve('@radix-ui/colors/package.json')),
      'utf8',
    ),
  ) as { version: string }
).version;

/*
  A scale is any export with a P3 light variant and a P3 dark one. Derived from
  the package rather than listed here, so a scale Radix adds is picked up on
  the next run. blackP3A and whiteP3A are alpha-only and have no dark pair.
*/
const scales = Object.keys(exports)
  .map((name) => /^([a-z]+)P3$/.exec(name)?.[1])
  .filter((name): name is string => Boolean(name))
  .filter((name) => exports[`${name}DarkP3`] !== undefined)
  .sort();

function declarations(name: string, theme: 'light' | 'dark') {
  const scale = exports[theme === 'light' ? `${name}P3` : `${name}DarkP3`];
  if (!scale) throw new Error(`@radix-ui/colors has no ${theme} ${name} scale`);
  const infix = theme === 'light' ? '' : 'dark-';
  return Array.from({ length: STEPS }, (_, index) => {
    const step = index + 1;
    const value = scale[`${name}${step}`];
    if (!value) throw new Error(`${name} ${theme} is missing step ${step}`);
    return `  --color-radix-${name}-${infix}${step}: ${value};`;
  });
}

const blocks = scales.map((name) =>
  [...declarations(name, 'light'), ...declarations(name, 'dark')].join('\n'),
);

const css = `/*
  Radix Colors ${version} (MIT), every scale at all twelve steps, light and dark.
  Generated by scripts/generate-radix-colors.ts -- do not edit by hand; run
  \`pnpm colors:radix\` after changing the package version.

  The dark scale is named \`-dark-\` rather than sharing the light names under a
  .dark class, so a colour picks its theme with light-dark(). P3 values, and
  inside @theme, so Tailwind emits only the variables something reads.
*/
@theme {
${blocks.join('\n\n')}
}
`;

writeFileSync(OUTPUT, css);
process.stdout.write(
  `app/radix-colors.css: ${scales.length} scales, ${scales.length * STEPS * 2} colours (Radix ${version})\n`,
);
